Update README.md
riverar/wsa-app-compatibility pull request #121
Opened 2022-03-30 17:26 UTC by james28909

2022-04-14 20:30 UTC, pratyakshm requested changes

2022-04-14 20:30 UTC, pratyakshm commented on README.md
> +| Home Assistant | 2022.3.0-full | ✅ | Havent tested everything yet, but seems like it works fine so far |
```suggestion
| Home Assistant | 2022.3.0-full | ✅ | Basic functionality works, additional / extended functionality has not been yet tested. |
```

2022-04-15 01:49 UTC, riverar commented on README.md
> +| Home Assistant | 2022.3.0-full | ✅ | Havent tested everything yet, but seems like it works fine so far |
```suggestion
| Home Assistant | 2022.3.0-full | ✅ | |
```

2022-04-15 01:57 UTC, merged

2022-04-15 01:57 UTC, riverar commented
Thanks!