Added several applications and games.
riverar/wsa-app-compatibility pull request #57
Opened 2021-11-03 07:27 UTC by ichlaffterlalu

Updated status:
- Arcaea with version 3.8.8

New applications:
- AIDE
- Duolingo
- Gojek
- Google Meet
- JAKI - Jakarta Kini
- JuiceSSH
- Khan Academy
- KRL Access
- Libby
- LinkedIn
- ManCityApp
- MOLA
- Moodle
- Network IP Scanner
- Vidio
- Zoom

New games:
- Bad Piggies HD
- BanG Dream
- Microsoft Wordament

2021-11-03 08:23 UTC, ichlaffterlalu commented
New applications:
- CamScanner
- Dcoder
- GeoGebra Graphing Calc
- iPusnas (National Library of Indonesia)
- Microsoft Azure
- QPython 3L
- Slack
- Symbolab
- Trello

2021-11-03 17:06 UTC, Ratulhasan14789 commented
OUT OF TOPIC, one question: how did you use both wsa and magisk (probably the GSM one) at the same time??

2021-11-03 18:44 UTC, pratyakshm requested changes

2021-11-03 18:44 UTC, pratyakshm commented on README.md
> +| AIDE | 3.2.210316 | ✅ | | Might require GMS. |
```suggestion
| AIDE | 3.2.210316 | ✅ | | Might optionally require GMS |
```

2021-11-03 18:44 UTC, pratyakshm commented on README.md
> +| Arcaea | 3.8.8 | ⚠️ | Keyboard doesn't work on login/register form. | |
```suggestion
| Arcaea | 3.8.8 | ⚠️ | Keyboard doesn't work on login/register form | |
```

2021-11-03 18:44 UTC, pratyakshm commented on README.md
> +| JuiceSSH | 3.2.2 | ⚠️ | Connecting to SSH server needs multiple tries. | |
```suggestion
| JuiceSSH | 3.2.2 | ⚠️ | Connecting to SSH server needs multiple tries | |
```

2021-11-03 18:44 UTC, pratyakshm commented on README.md
> +| KRL Access | 4.1.0 | ❌ | App crashes immedately. | |
```suggestion
| KRL Access | 4.1.0 | ❌ | App crashes | |
```

2021-11-03 18:44 UTC, pratyakshm commented on README.md
> +| Zenly (Without Google Services) | 4.55.2 | ⚠️ | App crashes after login, but background location works |
```suggestion
| Zenly (w/o GMS) | 4.55.2 | ⚠️ | App crashes after login, but background location works |
```

2021-11-03 18:48 UTC, merged

2021-11-03 18:48 UTC, pratyakshm commented
Thank you so much!

2021-11-04 01:07 UTC, ichlaffterlalu commented
> OUT OF TOPIC, one question: how did you use both wsa and magisk (probably the GSM one) at the same time??
@Ratulhassan14789 simply use one version at a time: install WSA-Magisk, then uninstall, then install vanilla WSA :D